#!/bin/sh

version="$1"
#sed -i "s/version = .*/version = ""$version""/g" lib/build.gradle.kts
#sed -i "s/com\.luissoares:selenium-testing-library:[0-9]\+\.[0-9]\+\.[0-9]\+/com.luissoares:selenium-testing-library:$version/g" README.md
git tag -l | xargs git tag -d
git push --delete origin "v$version"
git tag "v$version" -m "Tag release"
git push origin "v$version"